[package]
name = "mmdb2dat-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cidr-utils = "0.5.7"

[profile.release]
opt-level = 3
lto = true